module.exports = {
  apps: [
    {
      name: 'qianfan-protocol-daemon',
      script: 'scripts/qianfan-protocol-daemon.js',
      cwd: __dirname,
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      env: {
        NODE_ENV: 'production',
        QIANFAN_PROTOCOL_DAEMON_PORT: '9324',
        QIANFAN_PROTOCOL_DAEMON_HOST: '0.0.0.0',
      },
    },
    {
      name: 'qianfan-protocol-config-agent',
      script: 'scripts/qianfan-protocol-config-agent.js',
      cwd: __dirname,
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 100,
      restart_delay: 10000,
      env: {
        NODE_ENV: 'production',
        QIANFAN_PROTOCOL_SERVER_URL: 'http://127.0.0.1:9324',
      },
    },
    {
      name: 'qianfan-protocol-bridge',
      script: 'scripts/qianfan-protocol-bridge-server.js',
      cwd: __dirname,
      interpreter: 'node',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 100,
      restart_delay: 5000,
      env: {
        NODE_ENV: 'production',
        QIANFAN_PROTOCOL_BRIDGE_HOST: '0.0.0.0',
        QIANFAN_PROTOCOL_BRIDGE_PORT: '35872',
        QIANFAN_PROTOCOL_BRIDGE_PRODUCTION: '1',
        QIANFAN_SEND_ONLY_BUYER_NICK: '',
        QIANFAN_PROTOCOL_BRIDGE_SHOP: '祥钰珠宝',
      },
    },
  ],
};
